-- 机器人扩展配置
ALTER TABLE robots ADD COLUMN IF NOT EXISTS biz_ws_url VARCHAR(255) DEFAULT '';
ALTER TABLE robots ADD COLUMN IF NOT EXISTS enable_biz_ws BOOLEAN DEFAULT FALSE;
ALTER TABLE robots ADD COLUMN IF NOT EXISTS watch_folder VARCHAR(500) DEFAULT '';
ALTER TABLE robots ADD COLUMN IF NOT EXISTS enable_folder_watch BOOLEAN DEFAULT FALSE;
ALTER TABLE robots ADD COLUMN IF NOT EXISTS image_extensions VARCHAR(255) DEFAULT '.png,.jpg,.jpeg,.gif,.webp,.bmp';
